# Generated by Django 3.1.4 on 2021-04-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0004_genre_language_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
