# Generated by Django 3.1.4 on 2021-04-01 23:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0007_genre_language_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='json_file',
            field=jsonfield.fields.JSONField(),
        ),
    ]
