# Generated by Django 3.1.4 on 2021-04-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0010_auto_20210424_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frdictionary',
            name='lang_1',
        ),
        migrations.RemoveField(
            model_name='frdictionary',
            name='lang_2',
        ),
        migrations.RemoveField(
            model_name='frdictionary',
            name='lang_3',
        ),
        migrations.RemoveField(
            model_name='frdictionary',
            name='word_id',
        ),
        migrations.RemoveField(
            model_name='rudictionary',
            name='lang_1',
        ),
        migrations.RemoveField(
            model_name='rudictionary',
            name='lang_2',
        ),
        migrations.RemoveField(
            model_name='rudictionary',
            name='lang_3',
        ),
        migrations.RemoveField(
            model_name='rudictionary',
            name='word_id',
        ),
        migrations.RemoveField(
            model_name='spadictionary',
            name='lang_1',
        ),
        migrations.RemoveField(
            model_name='spadictionary',
            name='lang_2',
        ),
        migrations.RemoveField(
            model_name='spadictionary',
            name='lang_3',
        ),
        migrations.RemoveField(
            model_name='spadictionary',
            name='word_id',
        ),
        migrations.DeleteModel(
            name='ENDictionary',
        ),
        migrations.DeleteModel(
            name='FRDictionary',
        ),
        migrations.DeleteModel(
            name='FrenchWord',
        ),
        migrations.DeleteModel(
            name='RUDictionary',
        ),
        migrations.DeleteModel(
            name='RussianWord',
        ),
        migrations.DeleteModel(
            name='SPADictionary',
        ),
        migrations.DeleteModel(
            name='SpanishWord',
        ),
    ]
