# Generated by Django 3.1.4 on 2021-04-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0011_auto_20210424_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrenchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RussianWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpanishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SPADictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_lang1', to='langImport.language')),
                ('lang_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_lang2', to='langImport.language')),
                ('lang_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_lang3', to='langImport.language')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langImport.spanishword')),
            ],
        ),
        migrations.CreateModel(
            name='RUDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ru_lang1', to='langImport.language')),
                ('lang_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ru_lang2', to='langImport.language')),
                ('lang_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ru_lang3', to='langImport.language')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langImport.russianword')),
            ],
        ),
        migrations.CreateModel(
            name='FRDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_lang1', to='langImport.language')),
                ('lang_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_lang2', to='langImport.language')),
                ('lang_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_lang3', to='langImport.language')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langImport.frenchword')),
            ],
        ),
        migrations.CreateModel(
            name='ENDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_lang1', to='langImport.language')),
                ('lang_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_lang2', to='langImport.language')),
                ('lang_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_lang3', to='langImport.language')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langImport.englishword')),
            ],
        ),
    ]
