# Generated by Django 3.1.4 on 2021-04-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0012_endictionary_frdictionary_frenchword_rudictionary_russianword_spadictionary_spanishword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ENDictionary',
            new_name='EN_Dictionary',
        ),
    ]
