# Generated by Django 3.1.4 on 2021-04-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0013_auto_20210424_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EN_Dictionary',
            new_name='E_Dictionary',
        ),
    ]
