# Generated by Django 3.1.4 on 2021-04-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0014_auto_20210424_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='E_Dictionary',
            new_name='Edictionary',
        ),
    ]
