# Generated by Django 3.1.4 on 2021-04-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0015_auto_20210424_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FRDictionary',
            new_name='Fdictionary',
        ),
        migrations.RenameModel(
            old_name='RUDictionary',
            new_name='Rdictionary',
        ),
        migrations.RenameModel(
            old_name='SPADictionary',
            new_name='Sdictionary',
        ),
        migrations.AddField(
            model_name='frenchword',
            name='definition',
            field=models.TextField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='pron',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='word',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='word_class',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='russianword',
            name='definition',
            field=models.TextField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='russianword',
            name='pron',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='russianword',
            name='word',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='russianword',
            name='word_class',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='spanishword',
            name='definition',
            field=models.TextField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='spanishword',
            name='pron',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='spanishword',
            name='word',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='spanishword',
            name='word_class',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='pron',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
