# Generated by Django 3.1.4 on 2021-04-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0016_auto_20210424_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edictionary',
            name='lang_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_lang1', to='langImport.spanishword'),
        ),
        migrations.AlterField(
            model_name='edictionary',
            name='lang_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_lang2', to='langImport.russianword'),
        ),
        migrations.AlterField(
            model_name='edictionary',
            name='lang_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_lang3', to='langImport.frenchword'),
        ),
    ]
