# Generated by Django 3.1.4 on 2021-04-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0018_auto_20210424_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edictionary',
            old_name='lang_3',
            new_name='fr_id',
        ),
        migrations.RenameField(
            model_name='edictionary',
            old_name='lang_2',
            new_name='ru_id',
        ),
        migrations.RenameField(
            model_name='edictionary',
            old_name='lang_1',
            new_name='spa_id',
        ),
        migrations.RenameField(
            model_name='fdictionary',
            old_name='lang_1',
            new_name='en_id',
        ),
        migrations.RenameField(
            model_name='fdictionary',
            old_name='lang_3',
            new_name='ru_id',
        ),
        migrations.RenameField(
            model_name='fdictionary',
            old_name='lang_2',
            new_name='spa_id',
        ),
        migrations.RenameField(
            model_name='rdictionary',
            old_name='lang_1',
            new_name='en_id',
        ),
        migrations.RenameField(
            model_name='rdictionary',
            old_name='lang_3',
            new_name='fr_id',
        ),
        migrations.RenameField(
            model_name='rdictionary',
            old_name='lang_2',
            new_name='spa_id',
        ),
        migrations.RenameField(
            model_name='sdictionary',
            old_name='lang_1',
            new_name='en_id',
        ),
        migrations.RenameField(
            model_name='sdictionary',
            old_name='lang_3',
            new_name='fr_id',
        ),
        migrations.RenameField(
            model_name='sdictionary',
            old_name='lang_2',
            new_name='ru_id',
        ),
    ]
