# Generated by Django 3.1.4 on 2021-05-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0020_auto_20210430_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tdictionary',
        ),
    ]
