# Generated by Django 3.1.4 on 2021-05-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0021_delete_tdictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tdictionary',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('en_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang1', to='langImport.englishword')),
                ('fr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang4', to='langImport.frenchword')),
                ('ru_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang3', to='langImport.russianword')),
                ('spa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang2', to='langImport.spanishword')),
            ],
        ),
    ]
