# Generated by Django 3.1.4 on 2021-05-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langImport', '0025_auto_20210509_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='none', max_length=20)),
                ('definition', models.TextField(default='none', max_length=20)),
                ('word_class', models.CharField(default='none', max_length=20)),
                ('pron', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FrenchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='none', max_length=20)),
                ('definition', models.TextField(default='none', max_length=20)),
                ('word_class', models.CharField(default='none', max_length=20)),
                ('pron', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RussianWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='none', max_length=20)),
                ('definition', models.TextField(default='none', max_length=20)),
                ('word_class', models.CharField(default='none', max_length=20)),
                ('pron', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpanishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='none', max_length=20)),
                ('definition', models.TextField(default='none', max_length=20)),
                ('word_class', models.CharField(default='none', max_length=20)),
                ('pron', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tdictionary',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('en_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang1', to='langImport.englishword')),
                ('fr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang4', to='langImport.frenchword')),
                ('ru_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang3', to='langImport.russianword')),
                ('spa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang2', to='langImport.spanishword')),
            ],
        ),
    ]
